server:
  port: 8085

amap:
  key: 9be00c92bf761f26e41441740609a5ef
  sid: 1052368
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-map
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///service-map?characterEncoding=utf-8&serverTimeZone=GMT%2B8
    username: root
    password: 123456
